services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smartcatcher_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env.test
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-test:5432/smartcatcher_test
      REDIS_URL: redis://redis-test:6379
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./examples:/app/examples
      - ./bot:/app/bot
      - ./worker:/app/worker
      - ./tests:/app/tests
    command: pytest -v
